id: I188344A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T10:28:35+00:00'
last_modified: '2022-06-08T05:10:43.618397+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE63
  title: ཆོས་སྤྱོད་ཀྱི་རིམ་པ། ༼སོག་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    217E:
      image_group_id: I1KG16990
      title: ''
      total_pages: 717
      order: 1
      base_file: 217E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
