id: P005596
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:05:44.383110
source_metadata:
  id: bdr:W1EE63
  title: ཆོས་སྤྱོད་ཀྱི་རིམ་པ། ༼སོག་ཡིག༽
  author: ''
  volumes:
    66e010fe8ac24c698b65e2e50559a467:
      image_group_id: I1KG16990
      title: ''
      volume_number: 1
      total_pages: 717
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
